/* Content for "The Saints God Sends" frieze — the five-column table from
   Steve's essay (The_Saints_God_Sends_1.docx, July 6, 2026), verbatim.
   Fields: century, the visible crisis, the heresy or operative error of the
   age, and the characteristic form of holiness God gave in answer.
   The final entry is the open row — our own age — and differs in kind:
   `open: true` renders it distinct and its panel points into the substitutes
   taxonomy on holiness.html#why-replaced.
   The static table in saints.html is the no-JS text version of this data;
   keep the two in sync if the table changes. */

export const SAINTS = [
  {
    id: 'peter',
    name: 'Peter',
    century: '1st',
    crisis: 'Birth of the Church',
    error: 'Judaizing legalism (cf. Acts 15)',
    holiness: 'Apostolic fatherhood; courageous witness; pastoral charity',
  },
  {
    id: 'paul',
    name: 'Paul',
    century: '1st',
    crisis: 'Expansion of the Gospel',
    error: 'Judaizers; proto-Gnostic speculation at Colossae',
    holiness: 'Missionary zeal; union with Christ; spiritual fatherhood',
  },
  {
    id: 'anthony',
    name: 'Anthony of Egypt',
    century: '4th',
    crisis: 'Worldliness after the legalization of Christianity',
    error: 'Arianism (left the desert to support Athanasius)',
    holiness: 'Radical asceticism; contemplative withdrawal; spiritual combat',
  },
  {
    id: 'basil',
    name: 'Basil the Great',
    century: '4th',
    crisis: 'Arian crisis; disorder in monasticism',
    error: 'Arianism; denial of the Spirit’s divinity',
    holiness: 'Ordered community life; doctrinal fidelity; charity',
  },
  {
    id: 'augustine',
    name: 'Augustine',
    century: '4th–5th',
    crisis: 'Intellectual confusion',
    error: 'Manichaeism; Donatism; Pelagianism',
    holiness: 'Interior conversion; the primacy of grace; pastoral teaching',
  },
  {
    id: 'benedict',
    name: 'Benedict',
    century: '6th',
    crisis: 'Collapse of Roman civilization',
    error: 'Residual paganism',
    holiness: 'Stability; prayer; work; ordered community',
  },
  {
    id: 'gregory',
    name: 'Gregory the Great',
    century: '6th',
    crisis: 'Clerical decline',
    error: 'Simony; ambition in sacred office',
    holiness: 'Pastoral fatherhood; humility; service',
  },
  {
    id: 'bernard',
    name: 'Bernard of Clairvaux',
    century: '12th',
    crisis: 'Monastic complacency',
    error: 'Abelard’s rationalism; Catharism in Languedoc',
    holiness: 'Love of Christ; contemplation; reform through charity',
  },
  {
    id: 'dominic',
    name: 'Dominic',
    century: '13th',
    crisis: 'Heresy',
    error: 'Albigensianism (Catharism)',
    holiness: 'Truth united to holiness; preaching from contemplation',
  },
  {
    id: 'francis',
    name: 'Francis of Assisi',
    century: '13th',
    crisis: 'Wealth and spiritual tepidity',
    error: 'Cathar contempt for creation',
    holiness: 'Poverty; joy; conformity to Christ Crucified',
  },
  {
    id: 'aquinas',
    name: 'Thomas Aquinas',
    century: '13th',
    crisis: 'Intellectual fragmentation',
    error: 'Latin Averroism; the “double truth”',
    holiness: 'Contemplative wisdom; integration of faith and reason',
  },
  {
    id: 'catherine-siena',
    name: 'Catherine of Siena',
    century: '14th',
    crisis: 'Papal crisis at Avignon',
    error: 'Schismatic and conciliarist tendencies',
    holiness: 'Union with Christ; courageous truth spoken in charity',
  },
  {
    id: 'vincent-ferrer',
    name: 'Vincent Ferrer',
    century: '14th–15th',
    crisis: 'Western Schism',
    error: 'Schism; despair of the Church’s unity',
    holiness: 'Preaching; repentance; missionary conversion',
  },
  {
    id: 'ignatius',
    name: 'Ignatius of Loyola',
    century: '16th',
    crisis: 'Protestant Reformation',
    error: 'Protestantism; Illuminism (alumbrados)',
    holiness: 'Discernment; obedience; apostolic availability',
  },
  {
    id: 'teresa-avila',
    name: 'Teresa of Ávila',
    century: '16th',
    crisis: 'Religious mediocrity',
    error: 'Illuminist counterfeits of prayer',
    holiness: 'Interior prayer; contemplative reform; friendship with Christ',
  },
  {
    id: 'john-cross',
    name: 'John of the Cross',
    century: '16th',
    crisis: 'Superficial spirituality',
    error: 'False mysticism of the alumbrados',
    holiness: 'Purification; mystical union; abandonment',
  },
  {
    id: 'borromeo',
    name: 'Charles Borromeo',
    century: '16th',
    crisis: 'Post-Reformation clergy',
    error: 'Protestantism',
    holiness: 'Episcopal fatherhood; seminary reform; personal example',
  },
  {
    id: 'philip-neri',
    name: 'Philip Neri',
    century: '16th',
    crisis: 'Spiritual coldness in Rome',
    error: 'Worldliness of Renaissance humanism',
    holiness: 'Joy; friendship; gentle evangelization',
  },
  {
    id: 'de-sales',
    name: 'Francis de Sales',
    century: '17th',
    crisis: 'Lay discouragement; rigor',
    error: 'Calvinism (the Chablais mission); the rigorism that would ripen into Jansenism',
    holiness: 'Gentleness; universal call to holiness',
  },
  {
    id: 'vincent-de-paul',
    name: 'Vincent de Paul',
    century: '17th',
    crisis: 'Neglect of the poor and of clergy',
    error: 'Jansenism',
    holiness: 'Charity; practical mercy; priestly formation',
  },
  {
    id: 'john-eudes',
    name: 'John Eudes',
    century: '17th',
    crisis: 'Weak priestly formation',
    error: 'Jansenism',
    holiness: 'Priestly holiness; the Hearts of Jesus and Mary',
  },
  {
    id: 'margaret-mary',
    name: 'Margaret Mary Alacoque',
    century: '17th',
    crisis: 'Coldness toward Christ',
    error: 'Jansenism (the Sacred Heart as the divine answer)',
    holiness: 'Sacred Heart devotion; reparation; divine love',
  },
  {
    id: 'de-montfort',
    name: 'Louis de Montfort',
    century: '18th',
    crisis: 'Spiritual mediocrity',
    error: 'Jansenism',
    holiness: 'Total consecration to Jesus through Mary',
  },
  {
    id: 'liguori',
    name: 'Alphonsus Liguori',
    century: '18th',
    crisis: 'Moral rigorism',
    error: 'Jansenist rigorism',
    holiness: 'Mercy; pastoral theology; confidence in grace',
  },
  {
    id: 'vianney',
    name: 'John Vianney',
    century: '19th',
    crisis: 'Weak parish life',
    error: 'Post-revolutionary rationalism; Jansenist residue in the confessional',
    holiness: 'Prayer; penance; Confession; priestly fatherhood',
  },
  {
    id: 'bosco',
    name: 'John Bosco',
    century: '19th',
    crisis: 'Youth abandonment',
    error: 'Anticlerical liberalism; secularism',
    holiness: 'Fatherly love; education; the preventive system',
  },
  {
    id: 'therese',
    name: 'Thérèse of Lisieux',
    century: '19th',
    crisis: 'Spiritual elitism',
    error: 'Jansenist residue of fear and scrupulosity',
    holiness: 'Spiritual childhood; confidence; the little way',
  },
  {
    id: 'elizabeth-trinity',
    name: 'Elizabeth of the Trinity',
    century: '20th',
    crisis: 'Loss of interior life',
    error: 'Naturalism',
    holiness: 'The indwelling Trinity; recollection',
  },
  {
    id: 'kolbe',
    name: 'Maximilian Kolbe',
    century: '20th',
    crisis: 'Modern secularism',
    error: 'Militant atheism; Nazi ideology',
    holiness: 'Marian consecration; self-gift; evangelization',
  },
  {
    id: 'faustina',
    name: 'Faustina Kowalska',
    century: '20th',
    crisis: 'Despair after the world wars',
    error: 'Practical despair; distrust of God’s goodness',
    holiness: 'Trust in Divine Mercy',
  },
  {
    id: 'teresa-calcutta',
    name: 'Teresa of Calcutta',
    century: '20th',
    crisis: 'Indifference to human dignity',
    error: 'Materialism; the culture of indifference',
    holiness: 'Love of the poorest; hidden fidelity',
  },
  {
    id: 'john-paul-ii',
    name: 'John Paul II',
    century: '20th–21st',
    crisis: 'Secularization',
    error: 'Marxist collectivism; moral relativism',
    holiness: 'Holiness as pastoral priority; personalism; missionary confidence',
  },
  {
    id: 'our-own-age',
    name: 'Our Own Age',
    saint: 'Already given: Thérèse, Faustina, John Paul II',
    century: 'Our own',
    crisis: 'Pastoral decline beneath sincere effort',
    error: 'The substitutes: old errors under new names (trust in effort, in knowledge, in technique)',
    holiness: 'Trust in Divine Mercy under the primacy of grace (still to be received)',
    open: true,
  },
];
